### ISSUE TITLE
add sqlx-db-tester error

### ISSUE THREAD

**Issue by TeamMeng** [tyrchen/sqlx-db-tester#5]
when I use the sqlx about v0.8.2 and add sqlx-db-tester, it will error.
How to fix it?

error: failed to select a version for `libsqlite3-sys`.
    ... required by package `sqlx-sqlite v0.7.0`
    ... which satisfies dependency `sqlx-sqlite = "=0.7.0"` of package `sqlx v0.7.0`
    ... which satisfies dependency `sqlx = "^0.7"` of package `sqlx-db-tester v0.4.2`
    ... which satisfies dependency `sqlx-db-tester = "^0.4.2"` of package `chat-server v0.1.0 (/Users/Zhuanz/Dome/chat/chat_server)`
versions that meet the requirements `^0.26.0` are: 0.26.0

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.30.1`
    ... which satisfies dependency `libsqlite3-sys = "^0.30.1"` of package `sqlx-sqlite v0.8.2`
    ... which satisfies dependency `sqlx-sqlite = "=0.8.2"` of package `sqlx v0.8.2`
    ... which satisfies dependency `sqlx = "^0.8.2"` of package `chat-server v0.1.0 (/Users/Zhuanz/Dome/chat/chat_server)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "sqlite3"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `libsqlite3-sys` which could resolve this conflict

**Comment by tyrchen** [comment]
0.4.x only compatible with sqlx 0.7. Please use 0.5 (will be released soon).
